name: Unit tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      # see https://github.com/microsoft/setup-msbuild
      - name: Add msbuild to PATH
        if: startsWith(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: |
          pip install numpy Cython pytest pytest-benchmark

      - name: Install package
        shell: bash
        run: |
          python3 setup.py install --verbose

      - name: Test
        shell: bash
        run: |
          pytest tests

      - name: Benchmark
        shell: bash
        run: |
          pytest benchmark
